DATASET = siftsmall
ANNIMPORT_BASE_DATA_FILE = $(DATASET)/$(DATASET)_base.fvecs
ANNIMPORT_GROUNDTRUTH_DATA_FILE = $(DATASET)/$(DATASET)_groundtruth.ivecs
ANNIMPORT_QUERY_DATA_FILE = $(DATASET)/$(DATASET)_query.fvecs

ANNIMPORT_k = 100
ANNIMPORT_L = 250
ANNIMPORT_R = 60
ANNIMPORT_a = 1.2
